### ISSUE TITLE
[feat] run start + build concurrently

### ISSUE THREAD

**Issue by davidchase** [ghostmechanics/innards#1]
This is a neat setup 👍 any thoughts on using [concurrently](https://github.com/kimmobrunfeldt/concurrently) it allows you to run the build and start commands together without a need
for another tab/window its basically `npm run build & npm start` but with better handling of the spawned processes. I clone your repo and tried it locally worked pretty well and maintains
the `ctrl-c` to send `SIGINT` and kill the processes.

Thoughts?

**Comment by johnmichel** [comment]
Thanks for the 👍 !

I love this idea.  It's something I wanted to figure out cleanly, but had put on the backburner.  I'll definitely look into getting this going though.  Feel free to open a PR if you'd like.

**Comment by davidchase** [comment]
sounds good... will send up a PR 😄
